import React from 'react'
import { Container, Heading, Text, VStack } from '@chakra-ui/react'
import styles from '../styles/Home.module.css'
import TaskList from '../components/TaskList/TaskList'
import Head from 'next/head'

export default function CleaningSession() {
    return (
      <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-cleaning2.png" />
      </Head>

      <Container maxW={'80p'} justifyContent={'start'} className={styles.main}>
        <TaskList availableTime = {30} ></TaskList>
      </Container>

    </div>
    )
}
