import { Container, Heading } from '@chakra-ui/react'
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import TaskSchedule from '../components/TaskList/TaskSchedule'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>

      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon-cleaning2.png' />
      </Head>

      <Container maxW={{ base: 'full', md: '80p' }} justifyContent='start' className={styles.main}>
        <Heading>All Cleaning Tasks</Heading>
        <TaskSchedule sessionDuration={0} />
      </Container>

    </div>
  )
}

export default Home
