import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import TaskList from '../components/TaskList/TaskList'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-cleaning2.png" />
      </Head>

      <main className={styles.main}>
        <TaskList></TaskList>
      </main>

    </div>
  )
}

export default Home
