import React, { ReactElement } from 'react'
import { Container } from '@chakra-ui/react'
import styles from '../styles/Home.module.css'
import Head from 'next/head'

export default function TaskManager (): ReactElement {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon-cleaning2.png' />
      </Head>

      <Container maxW='80p' justifyContent='start' className={styles.main} />

    </div>
  )
}
